### ISSUE TITLE
Security : public exposition of students (and more) list

### ISSUE THREAD

**Issue by AYDEV-FR** [ISEN-Promo-Pole-developpement-Discord/Sigma-VI#35]
https://github.com/ISEN-Promo-Pole-developpement-Discord/Sigma-VI/blob/c8faefa0167d5fb9a4ebcbb8c30d6f8467c928fe/bot/requests/modules/planning/cacheManager.js#L6

# Proposal fix 
Add an authentication on this URL. Thx Willy :)

Another fix idea : Set this link in config file, and add this config file in ".gitignore" 👍 
But it's already committed oups....

**Comment by tom-bourjala** [comment]
Breach has been fixed: The leaked URL has been replaced by a new one.

New URL will be saved in the protected config file as suggested.

@Sigeth

**Comment by tom-bourjala** [comment]
All changes have been made as described.
Compromised URL is no longer supported and was terminated.
